### ISSUE TITLE
500 Error when project deployed with dynamic route at root of NextJS App Router project

### ISSUE THREAD

**Issue by hugheba** [RJPearson94/terraform-aws-open-next#28] opened 2024-05-01 20:10 UTC
## Technical Details

- OS: Ubuntu 24
- Terraform Version: 1.8.0
- Provider Version 2.1.4
- Module Version 2.41.
- Module Affected tf-aws-open-next-zone
- Deployment Model Single zone
- NextJS Version 14.1.4
- OpenNext Version 2.3.8

## Describe the bug

NextJS (App Router) Single Zone project deploys successfully but returns a 500 on the home page.

There is a catchall page that should be SSR'd pulling content from my headless CMS.

Looking at the error log on the Server Lambda function it reports the following error

`Error: Cannot find module '/var/task/.next/server/app/[[...slug]]/page.js'` (See full stack below)

I download the function Zip from ther Server Lambda view the contents and there is no .next folder only:

- cache.cjs
- index.mjs
- node_modules/
- package.json

I do see the file generated in the .open-next folder locally after running `open-next build` command but it is not making it into the function.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Create new NextJS project with App router
2. Install open-next
3. Create dynamic route at src/app/[[...slug]]/page.tsx and remove src/app/page.tsx
4. Follow instructions here to deploy https://github.com/RJPearson94/terraform-aws-open-next-examples/blob/main/single-zone/README.md

Example project here: https://github.com/hugheba/nextjs-open-next-dynamic-route-example

## Expected behaviour

Should render the page like it does locally.

## Logs

```
2024-05-01T19:55:40.023Z	0109bd8f-94ec-4669-91a7-9b06b5cde4a6	ERROR	 ⨯ Error: Cannot find module '/var/task/.next/server/app/[[...slug]]/page.js'
Require stack:
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requirePage (/var/task/node_modules/next/dist/server/require.js:109:84)
    at /var/task/node_modules/next/dist/server/load-components.js:98:84
    at async loadComponentsImpl (/var/task/node_modules/next/dist/server/load-components.js:98:26)
    at async NextNodeServer.findPageComponentsImpl (/var/task/node_modules/next/dist/server/next-server.js:710:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js'
  ]
}
```

**Comment by RJPearson94** [comment] 2024-05-01 22:00
Hi @hugheba, I have been able to re-create this. Looking into the root cause of the issue

**Comment by RJPearson94** [comment] 2024-05-02 17:56
Apologies for the delay. 
I think this might be a quirk of Terragrunt. When I removed terragrunt config and deployed the app using native terraform the app worked.

I added the following to a main.tf

```tf
data "aws_caller_identity" "current" {}

module "website" {
  source = "RJPearson94/open-next/aws//modules/tf-aws-open-next-zone"
  version = "2.3.0"

  prefix = "open-next-sz-${data.aws_caller_identity.current.account_id}"
  folder_path = "./.open-next"
  s3_exclusion_regex = ".*\\.terragrunt*"

  continuous_deployment = {
    use = true
    deployment = "NONE"
    traffic_config = {
      header = {
        name = "aws-cf-cd-staging"
        value = "true"
      }
    }
  }
  
  website_bucket = {
    force_destroy = true
  }

  providers = {
    aws.iam = aws.iam
    aws.global = aws.global
    aws.server_function = aws.server_function
    aws.dns = aws.dns
  }
}
```

This change will update all state references, so you may want to destroy the old app and deploy the new version using terraform.

I still want to get to the bottom of the terragrunt issue, so will continue looking

**Comment by RJPearson94** [comment] 2024-05-07 20:58
Hey @hugheba, have you managed to try out using native Terraform to see if this resolves your issue?

I am still looking into the issue with Terragrunt, its either something to do with the hidden folders or symlinks but not got to the bottom of it yet

**Comment by hugheba** [comment] 2024-05-07 21:00
@RJPearson94 Yes, sorry I forgot to reply but was able to get it working with Terraform. Actually wired it up with CDKTF and it worked fine..

Thanks for looking into the problem and providing workaround!

**Comment by RJPearson94** [comment] 2024-05-11 11:28
Closing issue, as this appears to be an issue with Terragrunt. 
The module works as expected when using native Terraform or CDKTF

**Closed by RJPearson94** 2024-05-11 11:28 UTC
